/*-
 * #%L
 * AEM Rules for SonarQube
 * %%
 * Copyright (C) 2015-2019 Cognifide Limited
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package com.cognifide.aemrules.java.util;

import java.util.Map;

public class ConstantsChecker {

    private static final Map<String, String> CONSTANTS = Map.ofEntries(
            // interface com.day.cq.commons.jcr.JcrConstants
            Map.entry("jcr:autoCreated", "JCR_AUTOCREATED from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:baseVersion", "JCR_BASEVERSION from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:child", "JCR_CHILD from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:childNodeDefinition", "JCR_CHILDNODEDEFINITION from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:content", "JCR_CONTENT from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:data", "JCR_DATA from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:defaultPrimaryType", "JCR_DEFAULTPRIMARYTYPE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:defaultValues", "JCR_DEFAULTVALUES from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:encoding", "JCR_ENCODING from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:frozenMixinTypes", "JCR_FROZENMIXINTYPES from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:frozenNode", "JCR_FROZENNODE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:frozenPrimaryType", "JCR_FROZENPRIMARYTYPE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:frozenUuid", "JCR_FROZENUUID from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:hasOrderableChildNodes", "JCR_HASORDERABLECHILDNODES from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:isCheckedOut", "JCR_ISCHECKEDOUT from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:isMixin", "JCR_ISMIXIN from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:language", "JCR_LANGUAGE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:lockIsDeep", "JCR_LOCKISDEEP from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:lockOwner", "JCR_LOCKOWNER from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:mandatory", "JCR_MANDATORY from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:mergeFailed", "JCR_MERGEFAILED from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:mimeType", "JCR_MIMETYPE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:mixinTypes", "JCR_MIXINTYPES from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:multiple", "JCR_MULTIPLE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:name", "JCR_NAME from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:nodeTypeName", "JCR_NODETYPENAME from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:onParentVersion", "JCR_ONPARENTVERSION from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:predecessors", "JCR_PREDECESSORS from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:primaryItemName", "JCR_PRIMARYITEMNAME from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:primaryType", "JCR_PRIMARYTYPE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:propertyDefinition", "JCR_PROPERTYDEFINITION from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:protected", "JCR_PROTECTED from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:requiredPrimaryTypes", "JCR_REQUIREDPRIMARYTYPES from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:requiredType", "JCR_REQUIREDTYPE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:rootVersion", "JCR_ROOTVERSION from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:sameNameSiblings", "JCR_SAMENAMESIBLINGS from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:statement", "JCR_STATEMENT from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:successors", "JCR_SUCCESSORS from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:supertypes", "JCR_SUPERTYPES from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:system", "JCR_SYSTEM from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:uuid", "JCR_UUID from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:valueConstraints", "JCR_VALUECONSTRAINTS from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:versionHistory", "JCR_VERSIONHISTORY from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:versionLabels", "JCR_VERSIONLABELS from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:versionStorage", "JCR_VERSIONSTORAGE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:versionableUuid", "JCR_VERSIONABLEUUID from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:path", "JCR_PATH from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:score", "JCR_SCORE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("mix:lockable", "MIX_LOCKABLE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("mix:referenceable", "MIX_REFERENCEABLE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("mix:versionable", "MIX_VERSIONABLE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:base", "NT_BASE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:childNodeDefinition", "NT_CHILDNODEDEFINITION from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:file", "NT_FILE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:folder", "NT_FOLDER from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:frozenNode", "NT_FROZENNODE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:hierarchyNode", "NT_HIERARCHYNODE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:linkedFile", "NT_LINKEDFILE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:nodeType", "NT_NODETYPE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:propertyDefinition", "NT_PROPERTYDEFINITION from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:query", "NT_QUERY from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:resource", "NT_RESOURCE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:unstructured", "NT_UNSTRUCTURED from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:version", "NT_VERSION from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:versionHistory", "NT_VERSIONHISTORY from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:versionLabels", "NT_VERSIONLABELS from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("nt:versionedChild", "NT_VERSIONEDCHILD from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("jcr:title", "JCR_TITLE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("mix:title", "MIX_TITLE from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("mix:created", "MIX_CREATED from interface com.day.cq.commons.jcr.JcrConstants"),
            Map.entry("mix:lastModified", "MIX_LAST_MODIFIED from interface com.day.cq.commons.jcr.JcrConstants"),

            // interface com.day.cq.dam.api.DamConstants
            Map.entry("dam:Asset", "NT_DAM_ASSET from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dam:AssetContent", "NT_DAM_ASSETCONTENT from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dam:extracted", "PN_EXTRACTED from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dam:sha1", "PN_SHA1 from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dam:size", "DAM_SIZE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("cq:versionCreator", "PN_VERSION_CREATOR from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:contributor", "DC_CONTRIBUTOR from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:coverage", "DC_COVERAGE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:creator", "DC_CREATOR from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:date", "DC_DATE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:description", "DC_DESCRIPTION from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:extent", "DC_EXTENT from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:format", "DC_FORMAT from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:identifier", "DC_IDENTIFIER from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:language", "DC_LANGUAGE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:modified", "DC_MODIFIED from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:publisher", "DC_PUBLISHER from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:relation", "DC_RELATION from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:rights", "DC_RIGHTS from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:subject", "DC_SUBJECT from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:title", "DC_TITLE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dc:type", "DC_TYPE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("cq5dam.thumbnail", "PREFIX_ASSET_THUMBNAIL from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("exif:PixelXDimension", "EXIF_PIXELXDIMENSION from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("exif:PixelYDimension", "EXIF_PIXELYDIMENSION from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("tiff:ImageLength", "TIFF_IMAGELENGTH from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("tiff:ImageWidth", "TIFF_IMAGEWIDTH from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("assetExpired", "ACTIVITY_TYPE_ASSET_EXPIRED from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("assetExpiring", "ACTIVITY_TYPE_ASSET_EXPIRING from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dam:lastPostExpirationRun", "LAST_EXPIRY_NOTIFICATION_PROPNAME from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dam/collection", "COLLECTION_SLING_RES_TYPE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dam/smartcollection", "SMART_COLLECTION_SLING_RES_TYPE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("dam/content/schemaeditors/forms", "SCHEMA_EDITOR_FORMS_BASE_DIR from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("processingProfile", "PROCESSING_PROFILE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("metadataProfile", "METADATA_PROFILE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("videoProfile", "VIDEO_PROFILE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("imageProfile", "IMAGE_PROFILE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("folderThumbnail", "THUMBNAIL_NODE from interface com.day.cq.dam.api.DamConstants"),
            Map.entry("downloadUrl", "DOWNLOAD_URL from interface com.day.cq.dam.api.DamConstants"),

            // interface com.day.cq.wcm.api.NameConstants
            Map.entry("cq:Page", "NT_PAGE from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:PseudoPage", "NT_PSEUDO_PAGE from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:Template", "NT_TEMPLATE from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:Component", "NT_COMPONENT from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:EditConfig", "NT_EDIT_CONFIG from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("dialog", "NN_DIALOG from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("dialogPath", "PN_DIALOG_PATH from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("design_dialog", "NN_DESIGN_DIALOG from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("designDialogPath", "PN_DESIGN_DIALOG_PATH from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:editConfig", "NN_EDIT_CONFIG from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:childEditConfig", "NN_CHILD_EDIT_CONFIG from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("icon.png", "NN_ICON_PNG from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("thumbnail.png", "NN_THUMBNAIL_PNG from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:cellName", "PN_CELL_NAME from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:isContainer", "PN_IS_CONTAINER from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:noDecoration", "PN_NO_DECORATION from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:htmlTag", "NN_HTML_TAG from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("allowedPaths", "PN_ALLOWED_PATHS from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("allowedChildren", "PN_ALLOWED_CHILDREN from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("allowedParents", "PN_ALLOWED_PARENTS from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("componentGroup", "PN_COMPONENT_GROUP from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("sitePath", "PN_SITE_PATH from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:templatePath", "PN_TEMPLATE_PATH from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:template", "NN_TEMPLATE from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:tagName", "PN_TAG_NAME from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:infoProviders", "NN_INFO_PROVIDERS from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("className", "PN_CLASS_NAME from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:disableTargeting", "PN_DISABLE_TARGETING from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:layout", "PN_LAYOUT from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:dialogMode", "PN_DIALOG_MODE from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:inplaceEditing", "NN_INPLACE_EDITING from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:emptyText", "PN_EMPTY_TEXT from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:actions", "PN_ACTIONS from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:actionConfigs", "NN_ACTION_CONFIGS from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:formParameters", "NN_FORM_PARAMETERS from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:dropTargets", "NN_DROP_TARGETS from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:listeners", "NN_LISTENERS from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("propertyName", "PN_DT_NAME from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:inherit", "PN_INHERIT from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:designPath", "PN_DESIGN_PATH from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:parentPath", "PN_PARENT_PATH from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:childrenOrder", "PN_CHILDREN_ORDER from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:siblingOrder", "PN_SIBLING_ORDER from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:versionComment", "PN_VERSION_COMMENT from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("onTime", "PN_ON_TIME from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("offTime", "PN_OFF_TIME from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:lastModified", "PN_PAGE_LAST_MOD from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:lastModifiedBy", "PN_PAGE_LAST_MOD_BY from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:defaultView", "PN_DEFAULT_VIEW from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("sling:vanityPath", "PN_SLING_VANITY_PATH from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:allowedTemplates", "PN_ALLOWED_TEMPLATES from interface com.day.cq.wcm.api.NameConstants"),

            // interface com.day.cq.wcm.webservicesupport.ConfigurationConstants
            Map.entry("cq/cloudserviceconfigs/components/servicepage", "RT_SERVICE from interface com.day.cq.wcm.webservicesupport.ConfigurationConstants"),
            Map.entry("cq/cloudserviceconfigs/components/configpage", "RT_CONFIGURATION from interface com.day.cq.wcm.webservicesupport.ConfigurationConstants"),
            Map.entry("cq:cloudserviceconfigs", "PN_CONFIGURATIONS from interface com.day.cq.wcm.webservicesupport.ConfigurationConstants"),

            // class org.apache.sling.jcr.resource.JcrResourceConstants
            Map.entry("http://sling.apache.org/jcr/sling/1.0", "SLING_NAMESPACE_URI from class org.apache.sling.jcr.resource.JcrResourceConstants"),
            Map.entry("sling:resourceType", "SLING_RESOURCE_TYPE_PROPERTY from class org.apache.sling.jcr.resource.JcrResourceConstants"),
            Map.entry("sling:resourceSuperType", "SLING_RESOURCE_SUPER_TYPE_PROPERTY from class org.apache.sling.jcr.resource.JcrResourceConstants"),
            Map.entry("user.jcr.credentials", "AUTHENTICATION_INFO_CREDENTIALS from class org.apache.sling.jcr.resource.JcrResourceConstants"),
            Map.entry("user.jcr.workspace", "AUTHENTICATION_INFO_WORKSPACE from class org.apache.sling.jcr.resource.JcrResourceConstants"),
            Map.entry("user.jcr.session", "AUTHENTICATION_INFO_SESSION from class org.apache.sling.jcr.resource.JcrResourceConstants"),
            Map.entry("sling:Folder", "NT_SLING_FOLDER from class org.apache.sling.jcr.resource.JcrResourceConstants"),
            Map.entry("sling:OrderedFolder", "NT_SLING_ORDERED_FOLDER from class org.apache.sling.jcr.resource.JcrResourceConstants"),

            // interface com.day.cq.tagging.TagConstants
            Map.entry("cq:Tag", "NT_TAG from interface com.day.cq.tagging.TagConstants"),
            Map.entry("cq:Taggable", "NT_TAGGABLE from interface com.day.cq.tagging.TagConstants"),
            Map.entry("cq:movedTo", "PN_MOVED_TO from interface com.day.cq.tagging.TagConstants"),
            Map.entry("cq:backlinks", "PN_BACKLINKS from interface com.day.cq.tagging.TagConstants"),

            // interface com.day.cq.replication.ReplicationStatus
            Map.entry("cq:ReplicationStatus", "NODE_TYPE from interface com.day.cq.replication.ReplicationStatus"),

            // interface org.apache.jackrabbit.vault.packaging.JcrPackage
            Map.entry("application/zip", "MIME_TYPE from interface org.apache.jackrabbit.vault.packaging.JcrPackage"),
            Map.entry("vlt:definition", "NN_VLT_DEFINITION from interface org.apache.jackrabbit.vault.packaging.JcrPackage"),
            Map.entry("vlt:Package", "NT_VLT_PACKAGE from interface org.apache.jackrabbit.vault.packaging.JcrPackage"),
            Map.entry("vlt:PackageDefinition", "NT_VLT_PACKAGE_DEFINITION from interface org.apache.jackrabbit.vault.packaging.JcrPackage"),

            // interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition
            Map.entry("acHandling", "PN_AC_HANDLING from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("buildCount", "PN_BUILD_COUNT from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("cndPattern", "PN_CND_PATTERN from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("dependencies", "PN_DEPENDENCIES from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("noIntermediateSaves", "PN_DISABLE_INTERMEDIATE_SAVE from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("lastUnpacked", "PN_LAST_UNPACKED from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("lastUnpackedBy", "PN_LAST_UNPACKED_BY from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("lastUnwrapped", "PN_LAST_UNWRAPPED from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("lastUnwrappedBy", "PN_LAST_UNWRAPPED_BY from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("lastWrapped", "PN_LAST_WRAPPED from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("lastWrappedBy", "PN_LAST_WRAPPED_BY from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("requiresRestart", "PN_REQUIRES_RESTART from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("requiresRoot", "PN_REQUIRES_ROOT from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("subPackages", "PN_SUB_PACKAGES from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),

            // interface org.apache.sling.api.resource.ResourceResolverFactory
            Map.entry("user.password", "PASSWORD from interface org.apache.sling.api.resource.ResourceResolverFactory"),
            Map.entry("sling.service.subservice", "SUBSERVICE from interface org.apache.sling.api.resource.ResourceResolverFactory"),
            Map.entry("user.name", "USER from interface org.apache.sling.api.resource.ResourceResolverFactory"),
            Map.entry("user.impersonation", "USER_IMPERSONATION from interface org.apache.sling.api.resource.ResourceResolverFactory"),

            // class com.adobe.granite.workflow.event.WorkflowEvent
            Map.entry("Delagatee", "DELEGATEE from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("EventType", "EVENT_TYPE from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("fromNodeName", "FROM_NODE_NAME from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("JobFailed", "JOB_FAILED_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("ModelDeleted", "MODEL_DELETED_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("ModelDeployed", "MODEL_DEPLOYED_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("NodeTransition", "NODE_TRANSITION_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("ParentWorkflowId", "PARENT_WORKFLOW_ID from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("ProcessTimeout", "PROCESS_TIMEOUT_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("ResourceCollectionModified", "RESOURCE_COLLECTION_MODIFIED from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("TimeStamp", "TIME_STAMP from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("toNodeName", "TO_NODE_NAME from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("User", "USER from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("VariableName", "VARIABLE_NAME from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("VariableUpdate", "VARIABLE_UPDATE_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("VariableValue", "VARIABLE_VALUE from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("Workdata", "WORK_DATA from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("Workitem", "WORK_ITEM from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowAborted", "WORKFLOW_ABORTED_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowCompleted", "WORKFLOW_COMPLETED_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowInstanceId", "WORKFLOW_INSTANCE_ID from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowName", "WORKFLOW_NAME from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowNode", "WORKFLOW_NODE from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowResumed", "WORKFLOW_RESUMED_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowStarted", "WORKFLOW_STARTED_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowSuspended", "WORKFLOW_SUSPENDED_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkflowVersion", "WORKFLOW_VERSION from class com.adobe.granite.workflow.event.WorkflowEvent"),
            Map.entry("WorkItemDelegated", "WORKITEM_DELEGATION_EVENT from class com.adobe.granite.workflow.event.WorkflowEvent"),

            // mix
            Map.entry("cq:lastReplicated",
                    "NODE_PROPERTY_LAST_REPLICATED from interface com.day.cq.replication.ReplicationStatus"
                            + " or constant PN_PAGE_LAST_REPLICATED from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:lastReplicatedBy",
                    "NODE_PROPERTY_LAST_REPLICATED_BY from interface com.day.cq.replication.ReplicationStatus"
                            + " or constant PN_PAGE_LAST_REPLICATED_BY from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:lastReplicationAction",
                    "NODE_PROPERTY_LAST_REPLICATION_ACTION from interface com.day.cq.replication.ReplicationStatus"
                            + " or constant PN_PAGE_LAST_REPLICATION_ACTION from interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:tags", "PN_TAGS from interface com.day.cq.tagging.TagConstants.PN_TAGS or interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("cq:name", "PN_NAME from interface com.day.cq.dam.api.DamConstants.PN_NAME or interface com.day.cq.wcm.api.NameConstants"),
            Map.entry("jcr:created",
                    "JCR_CREATED from interface com.day.cq.commons.jcr.JcrConstants"
                            + " or constant PN_CREATED from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("jcr:createdBy",
                    "JCR_CREATED_BY from interface com.day.cq.commons.jcr.JcrConstants"
                            + " or constant PN_CREATED_BY from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("jcr:description",
                    "JCR_DESCRIPTION from interface com.day.cq.commons.jcr.JcrConstants"
                            + " or constant PN_DESCRIPTION from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("jcr:lastModified",
                    "JCR_LASTMODIFIED from interface com.day.cq.commons.jcr.JcrConstants"
                            + " or constant PN_LASTMODIFIED from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition"),
            Map.entry("jcr:lastModifiedBy", "JCR_LAST_MODIFIED_BY from interface com.day.cq.commons.jcr.JcrConstants"
                    + " or constant PN_LASTMODIFIED_BY from interface org.apache.jackrabbit.vault.packaging.JcrPackageDefinition")
    );

    private static final Map<String, String> ANNOTATION_CONSTANTS = Map.ofEntries(
            // class org.apache.sling.api.SlingConstants
            Map.entry("org.apache.sling.api.include.servlet", "ATTR_REQUEST_SERVLET from class org.apache.sling.api.SlingConstants"),
            Map.entry("org.apache.sling.api.include.resource", "ATTR_REQUEST_CONTENT from class org.apache.sling.api.SlingConstants"),
            Map.entry("org.apache.sling.api.include.request_path_info", "ATTR_REQUEST_PATH_INFO from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.include.request_uri", "ATTR_INCLUDE_REQUEST_URI from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.include.context_path", "ATTR_INCLUDE_CONTEXT_PATH from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.include.servlet_path", "ATTR_INCLUDE_SERVLET_PATH from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.include.path_info", "ATTR_INCLUDE_PATH_INFO from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.include.query_string", "ATTR_INCLUDE_QUERY_STRING from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.error.exception", "ERROR_EXCEPTION from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.error.exception_type", "ERROR_EXCEPTION_TYPE from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.error.message", "ERROR_MESSAGE from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.error.request_uri", "ERROR_REQUEST_URI from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.error.servlet_name", "ERROR_SERVLET_NAME from class org.apache.sling.api.SlingConstants"),
            Map.entry("javax.servlet.error.status_code", "ERROR_STATUS from class org.apache.sling.api.SlingConstants"),
            Map.entry("org/apache/sling/api/resource/Resource/ADDED", "TOPIC_RESOURCE_ADDED from class org.apache.sling.api.SlingConstants"),
            Map.entry("org/apache/sling/api/resource/Resource/REMOVED", "TOPIC_RESOURCE_REMOVED from class org.apache.sling.api.SlingConstants"),
            Map.entry("org/apache/sling/api/resource/Resource/CHANGED", "TOPIC_RESOURCE_CHANGED from class org.apache.sling.api.SlingConstants"),
            Map.entry("org/apache/sling/api/resource/ResourceProvider/ADDED", "TOPIC_RESOURCE_PROVIDER_ADDED from class org.apache.sling.api.SlingConstants"),
            Map.entry("org/apache/sling/api/resource/ResourceProvider/REMOVED", "TOPIC_RESOURCE_PROVIDER_REMOVED from class org.apache.sling.api.SlingConstants"),
            Map.entry("org/apache/sling/api/resource/ResourceResolverMapping/CHANGED",
                    "TOPIC_RESOURCE_RESOLVER_MAPPING_CHANGED from class org.apache.sling.api.SlingConstants"),
            Map.entry("path", "PROPERTY_PATH from class org.apache.sling.api.SlingConstants"),
            Map.entry("userid", "PROPERTY_USERID from class org.apache.sling.api.SlingConstants"),
            Map.entry("resourceType", "PROPERTY_RESOURCE_TYPE from class org.apache.sling.api.SlingConstants"),
            Map.entry("resourceSuperType", "PROPERTY_RESOURCE_SUPER_TYPE from class org.apache.sling.api.SlingConstants"),
            Map.entry("resourceChangedAttributes", "PROPERTY_CHANGED_ATTRIBUTES from class org.apache.sling.api.SlingConstants"),
            Map.entry("resourceAddedAttributes", "PROPERTY_ADDED_ATTRIBUTES from class org.apache.sling.api.SlingConstants"),
            Map.entry("resourceRemovedAttributes", "PROPERTY_REMOVED_ATTRIBUTES from class org.apache.sling.api.SlingConstants"),
            Map.entry("org/apache/sling/api/adapter/AdapterFactory/ADDED", "TOPIC_ADAPTER_FACTORY_ADDED from class org.apache.sling.api.SlingConstants"),
            Map.entry("org/apache/sling/api/adapter/AdapterFactory/REMOVED", "TOPIC_ADAPTER_FACTORY_REMOVED from class org.apache.sling.api.SlingConstants"),
            Map.entry("adaptables", "PROPERTY_ADAPTABLE_CLASSES from class org.apache.sling.api.SlingConstants"),
            Map.entry("adapters", "PROPERTY_ADAPTER_CLASSES from class org.apache.sling.api.SlingConstants"),
            Map.entry("sling.core.current.servletName", "SLING_CURRENT_SERVLET_NAME from class org.apache.sling.api.SlingConstants"),

            // class org.apache.sling.api.servlets.HttpConstants
            Map.entry("OPTIONS", "METHOD_OPTIONS from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("GET", "METHOD_GET from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("HEAD", "METHOD_HEAD from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("POST", "METHOD_POST from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("PUT", "METHOD_PUT from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("DELETE", "METHOD_DELETE from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("TRACE", "METHOD_TRACE from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("CONNECT", "METHOD_CONNECT from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("Accept", "HEADER_ACCEPT from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("ETag", "HEADER_ETAG from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("If-Match", "HEADER_IF_MATCH from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("If-Modified-Since", "HEADER_IF_MODIFIED_SINCE from class org.apache.sling.api.servlets.HttpConstants"),
            Map.entry("Last-Modified", "HEADER_LAST_MODIFIED from class org.apache.sling.api.servlets.HttpConstants"),

            // interface org.osgi.framework.Constants
            Map.entry("System Bundle", "SYSTEM_BUNDLE_LOCATION from interface org.osgi.framework.Constants"),
            Map.entry("system.bundle", "SYSTEM_BUNDLE_SYMBOLICNAME from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-Category", "BUNDLE_CATEGORY from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-ClassPath", "BUNDLE_CLASSPATH from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-Copyright", "BUNDLE_COPYRIGHT from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-Description", "BUNDLE_DESCRIPTION from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-Name", "BUNDLE_NAME from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-NativeCode", "BUNDLE_NATIVECODE from interface org.osgi.framework.Constants"),
            Map.entry("Export-Package", "EXPORT_PACKAGE from interface org.osgi.framework.Constants"),
            Map.entry("Export-Service", "EXPORT_SERVICE from interface org.osgi.framework.Constants"),
            Map.entry("Import-Package", "IMPORT_PACKAGE from interface org.osgi.framework.Constants"),
            Map.entry("DynamicImport-Package", "DYNAMICIMPORT_PACKAGE from interface org.osgi.framework.Constants"),
            Map.entry("Import-Service", "IMPORT_SERVICE from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-Vendor", "BUNDLE_VENDOR from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-Version", "BUNDLE_VERSION from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-DocURL", "BUNDLE_DOCURL from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-ContactAddress", "BUNDLE_CONTACTADDRESS from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-Activator", "BUNDLE_ACTIVATOR from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-UpdateLocation", "BUNDLE_UPDATELOCATION from interface org.osgi.framework.Constants"),
            Map.entry("specification-version", "PACKAGE_SPECIFICATION_VERSION from interface org.osgi.framework.Constants"),
            Map.entry("processor", "BUNDLE_NATIVECODE_PROCESSOR from interface org.osgi.framework.Constants"),
            Map.entry("osname", "BUNDLE_NATIVECODE_OSNAME from interface org.osgi.framework.Constants"),
            Map.entry("osversion", "BUNDLE_NATIVECODE_OSVERSION from interface org.osgi.framework.Constants"),
            Map.entry("language", "BUNDLE_NATIVECODE_LANGUAGE from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-RequiredExecutionEnvironment", "BUNDLE_REQUIREDEXECUTIONENVIRONMENT from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-SymbolicName", "BUNDLE_SYMBOLICNAME from interface org.osgi.framework.Constants"),
            Map.entry("singleton", "SINGLETON_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("fragment-attachment", "FRAGMENT_ATTACHMENT_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("always", "FRAGMENT_ATTACHMENT_ALWAYS from interface org.osgi.framework.Constants"),
            Map.entry("resolve-time", "FRAGMENT_ATTACHMENT_RESOLVETIME from interface org.osgi.framework.Constants"),
            Map.entry("never", "FRAGMENT_ATTACHMENT_NEVER from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-Localization", "BUNDLE_LOCALIZATION from interface org.osgi.framework.Constants"),
            Map.entry("OSGI-INF/l10n/bundle", "BUNDLE_LOCALIZATION_DEFAULT_BASENAME from interface org.osgi.framework.Constants"),
            Map.entry("Require-Bundle", "REQUIRE_BUNDLE from interface org.osgi.framework.Constants"),
            Map.entry("bundle-version", "BUNDLE_VERSION_ATTRIBUTE from interface org.osgi.framework.Constants"),
            Map.entry("Fragment-Host", "FRAGMENT_HOST from interface org.osgi.framework.Constants"),
            Map.entry("selection-filter", "SELECTION_FILTER_ATTRIBUTE from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-ManifestVersion", "BUNDLE_MANIFESTVERSION from interface org.osgi.framework.Constants"),
            Map.entry("version", "VERSION_ATTRIBUTE from interface org.osgi.framework.Constants"),
            Map.entry("bundle-symbolic-name", "BUNDLE_SYMBOLICNAME_ATTRIBUTE from interface org.osgi.framework.Constants"),
            Map.entry("resolution", "RESOLUTION_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("optional", "RESOLUTION_OPTIONAL from interface org.osgi.framework.Constants"),
            Map.entry("uses", "USES_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("include", "INCLUDE_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("exclude", "EXCLUDE_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("mandatory", "MANDATORY_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("visibility", "VISIBILITY_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("private", "VISIBILITY_PRIVATE from interface org.osgi.framework.Constants"),
            Map.entry("reexport", "VISIBILITY_REEXPORT from interface org.osgi.framework.Constants"),
            Map.entry("extension", "EXTENSION_DIRECTIVE from interface org.osgi.framework.Constants"),
            Map.entry("framework", "EXTENSION_FRAMEWORK from interface org.osgi.framework.Constants"),
            Map.entry("bootclasspath", "EXTENSION_BOOTCLASSPATH from interface org.osgi.framework.Constants"),
            Map.entry("Bundle-ActivationPolicy", "BUNDLE_ACTIVATIONPOLICY from interface org.osgi.framework.Constants"),
            Map.entry("lazy", "ACTIVATION_LAZY from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.version", "FRAMEWORK_VERSION from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.vendor", "FRAMEWORK_VENDOR from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.language", "FRAMEWORK_LANGUAGE from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.os.name", "FRAMEWORK_OS_NAME from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.os.version", "FRAMEWORK_OS_VERSION from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.processor", "FRAMEWORK_PROCESSOR from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.executionenvironment", "FRAMEWORK_EXECUTIONENVIRONMENT from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.bootdelegation", "FRAMEWORK_BOOTDELEGATION from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.system.packages", "FRAMEWORK_SYSTEMPACKAGES from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.system.packages.extra", "FRAMEWORK_SYSTEMPACKAGES_EXTRA from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.supports.framework.extension", "SUPPORTS_FRAMEWORK_EXTENSION from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.supports.bootclasspath.extension", "SUPPORTS_BOOTCLASSPATH_EXTENSION from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.supports.framework.fragment", "SUPPORTS_FRAMEWORK_FRAGMENT from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.supports.framework.requirebundle", "SUPPORTS_FRAMEWORK_REQUIREBUNDLE from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.security", "FRAMEWORK_SECURITY from interface org.osgi.framework.Constants"),
            Map.entry("osgi", "FRAMEWORK_SECURITY_OSGI from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.storage", "FRAMEWORK_STORAGE from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.storage.clean", "FRAMEWORK_STORAGE_CLEAN from interface org.osgi.framework.Constants"),
            Map.entry("onFirstInit", "FRAMEWORK_STORAGE_CLEAN_ONFIRSTINIT from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.library.extensions", "FRAMEWORK_LIBRARY_EXTENSIONS from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.command.execpermission", "FRAMEWORK_EXECPERMISSION from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.trust.repositories", "FRAMEWORK_TRUST_REPOSITORIES from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.windowsystem", "FRAMEWORK_WINDOWSYSTEM from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.startlevel.beginning", "FRAMEWORK_BEGINNING_STARTLEVEL from interface org.osgi.framework.Constants"),
            Map.entry("org.osgi.framework.bundle.parent", "FRAMEWORK_BUNDLE_PARENT from interface org.osgi.framework.Constants"),
            Map.entry("service.id", "SERVICE_ID from interface org.osgi.framework.Constants"),
            Map.entry("service.pid", "SERVICE_PID from interface org.osgi.framework.Constants"),
            Map.entry("service.ranking", "SERVICE_RANKING from interface org.osgi.framework.Constants"),
            Map.entry("service.vendor", "SERVICE_VENDOR from interface org.osgi.framework.Constants"),
            Map.entry("service.description", "SERVICE_DESCRIPTION from interface org.osgi.framework.Constants"),

            // class org.apache.sling.engine.EngineConstants
            Map.entry("javax.servlet.Filter", "FILTER_NAME from class org.apache.sling.engine.EngineConstants"),
            Map.entry("sling.filter.scope", "SLING_FILTER_SCOPE from class org.apache.sling.engine.EngineConstants"),
            Map.entry("COMPONENT", "FILTER_SCOPE_COMPONENT from class org.apache.sling.engine.EngineConstants"),
            Map.entry("ERROR", "FILTER_SCOPE_ERROR from class org.apache.sling.engine.EngineConstants"),
            Map.entry("INCLUDE", "FILTER_SCOPE_INCLUDE from class org.apache.sling.engine.EngineConstants"),
            Map.entry("FORWARD", "FILTER_SCOPE_FORWARD from class org.apache.sling.engine.EngineConstants"),
            Map.entry("REQUEST", "FILTER_SCOPE_REQUEST from class org.apache.sling.engine.EngineConstants"),

            // class com.adobe.granite.workflow.event.WorkflowEvent
            Map.entry("com/adobe/granite/workflow/event", "EVENT_TOPIC from class com.adobe.granite.workflow.event.WorkflowEvent")
    );

    private ConstantsChecker() {
        // empty
    }

    public static boolean isAnnotationConstant(String value) {
        return ANNOTATION_CONSTANTS.containsKey(value);
    }

    public static String getAnnotationMessageForConstant(String value) {
        return ANNOTATION_CONSTANTS.get(value);
    }

    public static String getMessageForConstant(String value) {
        return CONSTANTS.get(value);
    }

    public static boolean isConstant(String value) {
        return CONSTANTS.containsKey(value);
    }

}
