#
# #%L
# AEM Rules for SonarQube
# %%
# Copyright (C) 2015-2019 Wunderman Thompson Technology
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #L%
#

name: 'Test plugin installation'
description: 'Installs AEM Rules on a SonarQube server to check if there are any runtime issues caused by dependencies'
on: [push]

jobs:
  build-and-test-docker-image:
    runs-on: ubuntu-latest
    env:
        SONARQUBE_VERSION: sonarqubr-8.9-community #Rename to SONARQUBE_BASE_IMAGE and match name?
        AEM_RULES_VERSION: 1.4-SNAPSHOT #TODO: Extract this dynamically?
    steps:
    - uses: actions/checkout@v2
    - name: Copy AEM Rules JAR
      run: |
        cp target/sonar-aemrules-plugin-1.4-SNAPSHOT.jar .github/actions/test-plugin-installation/sonar-aemrules-plugin-1.4-SNAPSHOT.jar
    - name: Build image
      run: docker build . -t ${SONARQUBE_VERSION,,}-${AEM_RULES_VERSION,,}
    - name: Test image
      run: ./run-tests.sh ${SONARQUBE_VERSION,,}-${AEM_RULES_VERSION,,}