name: build-and-analyse

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
      - name: Package the Maven project and analyse the AEM Rules code with SonarCloud
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: maven
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_KEY }}
        # The Sonar plugin automatically picks up the token from an env variable.
        # See https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-for-maven/#configuration
        run: mvn clean package jacoco:report coveralls:report sonar:sonar