name: build-and-analyse

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: maven
      - name: Package the Maven project and analyse the AEM Rules code with SonarCloud
        # The Sonar plugin automatically picks up the token from an env variable.
        # See https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-for-maven/#configuration
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_KEY }}
        run: mvn clean package \
             jacoco:report \
             coveralls:report \
             sonar:sonar -Dsonar.host.url=https://sonarcloud.io \
               -Dsonar.organization=wttech \
               -Dsonar.projectKey=wttech_AEM-Rules-for-SonarQube
